name: ELIZONPerms
api-version: 1.16
author: ELIZONMedia
database: true
load: STARTUP
website: https://elizon.app
main: app.elizon.perms.spigot.SpigotLoader
version: 0.5-beta
commands:
  ep:
    aliases:
      - elizonperms
      - perms
      - elizonp
    permission: elizonperms.command.execute